# Generated by Django 5.0.2 on 2024-03-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('fax', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=150)),
                ('smtpserver', models.CharField(max_length=25)),
                ('smtpemail', models.CharField(max_length=255)),
                ('smtppassword', models.CharField(max_length=255)),
                ('smtpport', models.CharField(max_length=10)),
                ('facebook', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=150)),
                ('twitter', models.CharField(max_length=150)),
                ('aboutus', models.TextField(max_length=255)),
                ('referances', models.TextField(max_length=255)),
            ],
        ),
    ]
