# Generated by Django 5.0.2 on 2024-03-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
