# Generated by Django 5.0.2 on 2024-03-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_settings_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.URLField(default='facebook', max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='linkedin',
            field=models.URLField(default='linkedin', max_length=150),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitter',
            field=models.URLField(default='twitter', max_length=150),
        ),
    ]
