# Generated by Django 5.0.2 on 2024-03-12 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='markalar',
            new_name='Brands',
        ),
        migrations.CreateModel(
            name='Ilanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner', models.ImageField(blank=True, upload_to='images/')),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('True', 'Aktif'), ('False', 'Deaktif')], default='False', max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilanlar.brands')),
            ],
        ),
    ]
