# Generated by Django 5.0.2 on 2024-03-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0002_rename_markalar_brands_ilanlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilanlar',
            name='horsepower',
            field=models.IntegerField(default=10),
        ),
    ]
