# Generated by Django 5.0.2 on 2024-03-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0003_ilanlar_horsepower'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilanlar',
            name='Gearbox',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='False', max_length=10),
        ),
        migrations.AddField(
            model_name='ilanlar',
            name='km',
            field=models.IntegerField(default=0),
        ),
    ]
