# Generated by Django 5.0.2 on 2024-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0004_ilanlar_gearbox_ilanlar_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilanlar',
            name='model',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='ilanlar',
            name='Gearbox',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ilanlar',
            name='km',
            field=models.IntegerField(),
        ),
    ]
