# Generated by Django 5.0.2 on 2024-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0005_ilanlar_model_alter_ilanlar_gearbox_alter_ilanlar_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilanlar',
            name='model',
            field=models.DateField(),
        ),
    ]
