# Generated by Django 5.0.2 on 2024-03-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0006_alter_ilanlar_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilanlar',
            name='model',
            field=models.PositiveSmallIntegerField(default=1900),
        ),
    ]
