# Generated by Django 5.0.2 on 2024-03-12 20:21

import ilanlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0008_ilanlar_goruntulenme_sayisi_alter_ilanlar_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilanlar',
            name='slug',
            field=models.SlugField(default=ilanlar.models.Ilanlar.generate_slug, unique=True),
        ),
    ]
