# Generated by Django 5.0.2 on 2024-03-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0009_alter_ilanlar_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlanResimleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('ilanlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilanlar.ilanlar')),
            ],
        ),
    ]
