# Generated by Django 5.0.2 on 2024-03-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0010_ilanresimleri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IlanResimleri',
        ),
    ]
