# Generated by Django 5.0.2 on 2024-03-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilanlar', '0012_image_remove_ilanlar_images_ilanlar_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilanlar',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='ilanlar',
            name='images',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
